### ISSUE TITLE
Перестал работать

### ISSUE THREAD

**Issue by Evil1991** [asminog/WebIcqPro#6]
Библиотека перестала отправлять сообщения примерно с 24.07.2015
Скажите, вы у себя эту проблему заметили? Или она частный характер носит?

**Comment by lyskouski** [comment]
Доброго дня,

>> Скажите, вы у себя эту проблему заметили? Или она частный характер носит?
Да, в собственном сервисе, который рассылает сообщения исходя из подписок
пользователей.

После некоторых вариаций её удалось идентифицировать:
- возвращалась 451 ошибка от сервера
- поиск указывал на то, что требуется пройти капчу на сайте
- получить саму ссылку из сообщения для валидации через скрипт не удалось
(ровно как через другие приложения: web ICQ, kopette)

Проблему удалось решить через телефон (с установкой туда ICQ, валидацией
через SMS), и при отсылке другому пользователю сообщения появилась
необходимая ссылка с капчей.

Прощу прощения за беспокойства. Судя по всему, это не новая проблема, а
эпизодическая проверка аккаунтов ICQ.

Спасибо.


27 июля 2015 г., 12:37 пользователь Evil1991 <notifications@github.com>
написал:

> Библиотека перестала отправлять сообщения примерно с 24.07.2015
> Скажите, вы у себя эту проблему заметили? Или она частный характер носит?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asminog/WebIcqPro/issues/6>.
>



-- 
С уважением,
Вячеслав Лысковский <deus@creativity.by>

**Comment by Evil1991** [comment]
lyskouski, а не могли бы подсказать, где проходить валидацию на мобильном клиенте? Я так понял он её не требует?

**Comment by lyskouski** [comment]
Когда отправляется сообщение любому пользователю, то в ответ приходит
сообщение (к сожалению, точную формулировку не подскажу):

Неизвестная ошибка #451. Перейдите

*по ссылке*
Ссылка ведет на сайт icq.com с капчей.

27 июля 2015 г., 15:50 пользователь Evil1991 <notifications@github.com>
написал:

> lyskouski, а не могли бы подсказать, где проходить валидацию на мобильном
> клиенте? Я так понял он её не требует?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asminog/WebIcqPro/issues/6#issuecomment-125194245>.
>



-- 
С уважением,
Вячеслав Лысковский <deus@creativity.by>

**Comment by Evil1991** [comment]
А я правильно понимаю, что из обычного клиента у вас тоже сообщения не отправлялись? Потому как у меня отправляются, но через WEB не в какую

**Comment by lyskouski** [comment]
Клиент даже не хотел подключаться (kopete), Web ICQ (
http://www.icq.com/download/webicq/ru) выдавал "Неизвестная ошибка 451" без
ссылки.

27 июля 2015 г., 17:00 пользователь Evil1991 <notifications@github.com>
написал:

> А я правильно понимаю, что из обычного клиента у вас тоже сообщения не
> отправлялись? Потому как у меня отправляются, но через WEB не в какую
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asminog/WebIcqPro/issues/6#issuecomment-125216923>.
>



-- 
С уважением,
Вячеслав Лысковский <deus@creativity.by>

**Comment by Evil1991** [comment]
Ясно, большое спасибо. У нас видимо иная проблема.

Т.е. сейчас у вас через эту библиотеку все сообщения отправляются?

**Comment by lyskouski** [comment]
Да, все работает.

27 июля 2015 г., 17:15 пользователь Evil1991 <notifications@github.com>
написал:

> Ясно, большое спасибо. У нас видимо иная проблема.
>
> Т.е. сейчас у вас через эту библиотеку все сообщения отправляются?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asminog/WebIcqPro/issues/6#issuecomment-125221199>.
>



-- 
С уважением,
Вячеслав Лысковский <deus@creativity.by>

**Comment by asminog** [comment]
Скрипт работает.

**Comment by asminog** [comment]
Скрипт работает, проверено 30.07.2015
