### ISSUE TITLE
"Server close connection" при подключении

### ISSUE THREAD

**Issue by artem78** [asminog/WebIcqPro#7]
При подключении выдаёт ошибку: Error: Server close connection. Смена сервера на slogin.icq.com:5190 и другие не помогает. Что делать?

**Comment by lyskouski** [comment]
Увеличь значения $this->timeout_second и $this->timeout_msecond в функции socetRead

**Comment by lyskouski** [comment]
В конструкторе класса WebIcqPro_Socet увеличь лимиты:
// $this->setTimeout(6, 0);
$this->setTimeout(60, 60000); // наобум взял, лучше постепенно увеличивать до восстановления работы сервиса

**Comment by artem78** [comment]
Помогло. Спасибо!

**Comment by asminog** [comment]
Fixed.
