### ISSUE TITLE
Doesn't work, unable to connect to login.icq.com

### ISSUE THREAD

**Issue by Jerome47** [asminog/WebIcqPro#9]
The error is: fsockopen(): unable to connect to login.icq.com:5190 (No route to host)
I've tried to change a $this->setTimeout(30, 0); in anyway, even $this->setTimeout(60, 60000); but it doesn't work, unfortunately.

**Comment by maxtorchel** [comment]
i have tha same issue

**Comment by asminog** [comment]
Check firewall settings, port closed?
Try port 80, add
`	$icq->setOption('ServerPort', 80);`
right after WebIcqPro object created and before connect.
